appname = agora_aevaluacion_docente_crudpi_crud
runmode = ${EVALUACION_DOCENTE_CRUD_RUN_MODE||prod}
httpport = ${EVALUACION_DOCENTE_CRUD_HTTP_PORT}
autorender = false
copyrequestbody = true

parameterStore = ${PARAMETER_STORE}
PGuser=${EVALUACION_DOCENTE_CRUD_PGUSER}
PGpass=${EVALUACION_DOCENTE_CRUD_PGPASS}
PGhost=${EVALUACION_DOCENTE_CRUD_PGHOST}
PGport=${EVALUACION_DOCENTE_CRUD_PGPORT}
PGdb=${EVALUACION_DOCENTE_CRUD_PGDB}
PGschema=${EVALUACION_DOCENTE_CRUD_PGSCHEMA}